import { Sparkles } from "lucide-react";

/**
 * Demo TL;DR card. Strips HTML and clips the first ~280 chars of the
 * article body. In a real Pro+ deployment, Morph's auto-TLDR engine
 * fills this from the Claude-generated summary instead.
 */
export function TLDRSummary({ summary }: { summary: string }) {
  return (
    <div className="card relative mb-10 p-6 overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-[color:color-mix(in_srgb,var(--primary)_5%,transparent)] via-transparent to-[color:color-mix(in_srgb,#a855f7_4%,transparent)] pointer-events-none" />
      <div className="relative">
        <div className="flex items-center gap-2 mb-2.5">
          <span className="grid place-items-center w-5 h-5 rounded-full bg-primary-soft border border-[color:color-mix(in_srgb,var(--primary)_22%,transparent)]">
            <Sparkles className="w-3 h-3 text-primary" strokeWidth={2.5} />
          </span>
          <span className="text-[10px] uppercase tracking-[0.18em] font-semibold text-primary">
            AI Summary · Generated by Morph
          </span>
        </div>
        <p className="text-[15px] leading-relaxed text-foreground">{summary}</p>
      </div>
    </div>
  );
}
